#' Estimates the gcc value for a region of interest
#' automatically generated by any given algorithm
#'
#' @param img: RGB image to process (filename or 3-layer RGB stack or brick)
#' @param plot: plot resulting image with all available information
#' @keywords gcc calculation
#' @export
#' @examples
#' # no examples yet

calculate_gcc = function(img,
                         roi = NULL){

  # set default file type
  file_type = "img"

  # verify data formats if not transform
  # to the correct data format
  if (class(img) == "character"){

    # set file type
    file_type = "file"

    # read in the image to estimate the region of interest of
    img = raster::brick(img)
  }

  # additional check if the stack / brick has three layers
  if (raster::nlayers(img) != 3){
    stop("the raster object does not have the required 3 (RGB) layers!")
  }

  # in case the image is in portrait mode, transpose and flip
  # to the correct landscape mode
  if (ncol(img) < nrow(img)){
    img = t( raster::flip(img,1) )
  }

  # if no roi is specified calcualte the roi
  if (is.null(roi)){
    # estimate an ROI
    roi_data = estimate_roi(img, plot = plot)
    
    # split out the roi and horizon data
    roi = roi_data$roi
  }
  
  # select the ROI from the original image
  img_region = mask(img,roi)
  
  # calculate various indices
  gcc = raster::subset(img_region,2) / sum(img_region)
  grvi = (raster::subset(img_region,2) -  raster::subset(img_region,1)) /
    (raster::subset(img_region,2) + raster::subset(img_region,1))

  # gcc 90 (90th percentile)
  gcc_90 = quantile(gcc, 0.9)

  # GRVI (10th percentile)
  grvi_10 = quantile(grvi, 0.1)

  # return values as a structure list
  return(list("roi" = roi,
              "horizon" = roi_data$horizon,
              "gcc" = gcc_90,
              "grvi" = grvi_10))
}
