#' Estimates the gcc value for a region of interest
#' automatically generated by any given algorithm
#'
#' @param img: RGB image to process (filename or 3-layer RGB stack or brick)
#' @param plot: plot resulting image with all available information
#' @keywords gcc calculation
#' @export
#' @examples
#' # no examples yet

estimate.gcc = function(img,
                        plot = FALSE){

  # set default file type
  file_type = "img"

  # verify data formats if not transform
  # to the correct data format
  if (class(img) == "character"){

    # set file type
    file_type = "file"

    # read in the image to estimate the region of interest of
    img = raster::brick(img)
  }

  # additional check if the stack / brick has three layers
  if (nlayers(img) != 3){
    stop("the raster object does not have the required 3 (RGB) layers!")
  }

  # in case the image is in portrait mode, transpose and flip
  # to the correct landscape mode
  if (ncol(img) < nrow(img)){
    img = t(
      raster::flip(img,1)
    )
  }

  # estimate an ROI
  roi_data = estimate.roi(img, plot = plot)

  # split out the roi and horizon data
  roi = roi_data$roi
  horizon = roi_data$horizon

  # calculate the gcc values for this ROI
  img_region = intersect(img,roi)

  # calculate various indices
  gcc = raster::subset(img,2) / sum(img)
  grvi = (raster::subset(img,2) -  raster::subset(img,1)) /
    (raster::subset(img,2) + raster::subset(img,1))

  # gcc 90 (90th percentile)
  gcc_90 = quantile(gcc,0.9)

  # GRVI (10th percentile)
  grvi_10 = quantile(grvi, 0.1)

  # return values as a structure list
  return(list("roi"=roi,"horizon"=horizon,"gcc"=gcc_90,"grvi"=grvi_10))
}

setwd('/data/Dropbox/Research_Projects/IFPRI/data/226129/2df3a94f-26c4-4c27-a30e-f3bc895dc5a/')
files = list.files(".","*.jpg")
img = files[1]

bla = estimate.gcc(img, plot = TRUE)
